// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';

/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQhpyUkCOVYMwIAj3HoIlsY2PEraxiP64',
    appId: '1:46760028645:web:99bf2354aee88f071de70c',
    messagingSenderId: '46760028645',
    projectId: 'beasiswa-79e05',
    authDomain: 'beasiswa-79e05.firebaseapp.com',
    storageBucket: 'beasiswa-79e05.appspot.com',
    measurementId: 'G-FVD8C49FTY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpw-Abo7jSM8jif11D7On7pLtOCbl_-_E',
    appId: '1:46760028645:android:26591e47a5c4a7e41de70c',
    messagingSenderId: '46760028645',
    projectId: 'beasiswa-79e05',
    storageBucket: 'beasiswa-79e05.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqKvDb91fqpXiE7C2l5Q7BsdHTH9A8We4',
    appId: '1:46760028645:ios:cf00f3e4dd56cc281de70c',
    messagingSenderId: '46760028645',
    projectId: 'beasiswa-79e05',
    storageBucket: 'beasiswa-79e05.appspot.com',
    iosBundleId: 'com.example.utsProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqKvDb91fqpXiE7C2l5Q7BsdHTH9A8We4',
    appId: '1:46760028645:ios:cf00f3e4dd56cc281de70c',
    messagingSenderId: '46760028645',
    projectId: 'beasiswa-79e05',
    storageBucket: 'beasiswa-79e05.appspot.com',
    iosBundleId: 'com.example.utsProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQhpyUkCOVYMwIAj3HoIlsY2PEraxiP64',
    appId: '1:46760028645:web:b0f0837959294eea1de70c',
    messagingSenderId: '46760028645',
    projectId: 'beasiswa-79e05',
    authDomain: 'beasiswa-79e05.firebaseapp.com',
    storageBucket: 'beasiswa-79e05.appspot.com',
    measurementId: 'G-HHL9JXFX4S',
  );
}
